const actionTypes = {
  EXAMPLE_FAILURE: 'EXAMPLE_FAILURE',
  EXAMPLE_INCREMENT: 'EXAMPLE_INCREMENT',
  EXAMPLE_DECREMENT: 'EXAMPLE_DECREMENT',
  EXAMPLE_RESET: 'EXAMPLE_RESET',
  EXAMPLE_LOAD_DATA: 'EXAMPLE_LOAD_DATA',
  EXAMPLE_LOAD_DATA_SUCCESS: 'EXAMPLE_LOAD_DATA_SUCCESS',
  EXAMPLE_START_CLOCK: 'EXAMPLE_START_CLOCK',
  EXAMPLE_TICK_CLOCK: 'EXAMPLE_TICK_CLOCK',
}

export default actionTypes
